### PR TITLE
Analyses

### PR DESCRIPTION
**Pull request by tyarkoni**
All basic custom analysis functionality in place. Hooray!

### CODE REVIEW

**Comment by r03ert0** [comment]
congratulations!!!
:)

**Comment by tyarkoni** [comment]
@r03ert0 thanks! And now onto the next (more difficult) step: annotation and editable studies! I'll email you to touch base about brainspell integration etc...

**Comment by tyarkoni** [comment]
Also, most of the credit for the new features belongs to @skept. :)

**Comment by vsoch** [comment]
Congrats!!

**Pull request merged**
